### ISSUE TITLE
ブラウザ毎に問題を保存している？

### ISSUE THREAD

**Issue by y-kob** [hayatob04/quiz-app#4]
ブラウザ毎に保存先が異なるようです。

Microsoft Edge と Google Chrome でそれぞれ別の問題を保存すると
表示するブラウザによって、問題が異なる。

※想定通りであれば、クローズしてください。

**Comment by hayatob04** [comment]
はい。ブラウザ毎のデータになります。
いまは、ブラウザのlocalStorageに保存しているためです。

保存されたデータを見るには、Chromeだと、
デベロッパー ツール(F12) -> Application タブ -> Storage - Local Storage　で確認できます。
